export default {
    PLAYER_START_Y_POS: 30,
    PLAYER_INITIAL_ROTATION: 0,
    INITIAL_VELOCITY: 0,
    JUMP_VELOCITY: -0.05,
    MAX_VELOCITY: 0.06,
    OBSTACLE_VELOCITY: 0.02,
    OBSTACLE_START_X_POS: 100,
    GRAVITY_ACCELERATION: 0.00008,
    // GRAVITY_ACCELERATION: 0, // FIXME delete
};
