export default {
    PLAYER_START_Y_POS: 30,
    PLAYER_INITIAL_ROTATION: "0deg",
    INITIAL_VELOCITY: 0,
    JUMP_VELOCITY: -0.09,
    MAX_VELOCITY: 0.08,
    OBSTACLE_VELOCITY: 0.015,
    ACCELERATION: 0.0002,
};
